#**Experiment 1: Introduction To Pandas And Introduction To Numpy**

# 1.1 Introduction To Numpy

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a.shape


(3, 5)

In [4]:
 a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
 a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)


numpy.ndarray

In [9]:
 b = np.array([6, 7, 8])


In [10]:
b


array([6, 7, 8])

In [11]:
type(b)


numpy.ndarray

In [12]:
b.dtype


dtype('int64')

In [13]:
c = np.array([[1, 2], [3, 4]], dtype=complex)


In [14]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
c.dtype.name

'complex128'

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty((2, 3))


array([[4.66943349e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [19]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [21]:
np.arange(0, 2, 0.3)


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
np.linspace(0, 2, 9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
np.arange(0, 11, 1)**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [24]:
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
print(a.reshape(5, 3))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [26]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [27]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])


In [28]:
A+B

array([[3, 1],
       [3, 5]])

In [29]:
A-B

array([[-1,  1],
       [-3, -3]])

In [30]:
A*B

array([[2, 0],
       [0, 4]])

In [31]:
A @ B

array([[5, 4],
       [3, 4]])

In [32]:
A/B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.5 ,  inf],
       [0.  , 0.25]])

In [33]:
 np.sin(np.arange(0, 2 * np.pi, np.pi / 6))

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  5.00000000e-01,  1.22464680e-16, -5.00000000e-01,
       -8.66025404e-01, -1.00000000e+00, -8.66025404e-01, -5.00000000e-01])

In [34]:
A.dot(B)


array([[5, 4],
       [3, 4]])

In [35]:
a[:6:2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [36]:
a[::-1]


array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [37]:
a[::-1]


array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [38]:
 A.trace()

2

In [39]:
A[0][[False, True]]


array([1])

# 1.2 Introduction To Pandas

In [40]:
import pandas as pd

In [41]:
s = pd.Series([1,3, 5, np.nan, 6, 8])


In [42]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [43]:
dates = pd.date_range('20130101', periods=6)


In [44]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [45]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))


In [46]:
df

A         B         C         D
2013-01-01  0.246267  1.989041  1.622371 -1.655383
2013-01-02  0.617953  0.780909  0.144204 -1.009016
2013-01-03  1.392900 -1.336249 -0.314047  1.602269
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122
2013-01-05 -0.370925  0.623369  0.636178  0.077903
2013-01-06 -0.197939 -0.783883 -0.887962 -0.654281

In [47]:
df2 = pd.DataFrame({
'A' : 1.0,
'B' : pd.Timestamp('20130102'),
'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
'D' : np.array([3] * 4, dtype='int32'),
'E' : pd.Categorical(['test', 'train', 'test', 'train']),
'F' : 'foo'
})

In [48]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [49]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [50]:
df.head()

A         B         C         D
2013-01-01  0.246267  1.989041  1.622371 -1.655383
2013-01-02  0.617953  0.780909  0.144204 -1.009016
2013-01-03  1.392900 -1.336249 -0.314047  1.602269
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122
2013-01-05 -0.370925  0.623369  0.636178  0.077903

In [51]:
df.tail(3)

A         B         C         D
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122
2013-01-05 -0.370925  0.623369  0.636178  0.077903
2013-01-06 -0.197939 -0.783883 -0.887962 -0.654281

In [52]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [53]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [54]:
df.to_numpy()

array([[ 0.24626705,  1.98904088,  1.62237067, -1.6553834 ],
       [ 0.61795308,  0.78090933,  0.14420434, -1.00901582],
       [ 1.39290005, -1.33624861, -0.31404697,  1.60226865],
       [-0.16067314, -0.48017366, -0.59888881, -0.28512197],
       [-0.37092496,  0.62336912,  0.63617839,  0.07790301],
       [-0.19793877, -0.7838831 , -0.88796207, -0.65428143]])

In [55]:
df2.to_numpy()


array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [56]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.254597  0.132169  0.100309 -0.320605
std    0.662774  1.223150  0.921195  1.115741
min   -0.370925 -1.336249 -0.887962 -1.655383
25%   -0.188622 -0.707956 -0.527678 -0.920332
50%    0.042797  0.071598 -0.084921 -0.469702
75%    0.525032  0.741524  0.513185 -0.012853
max    1.392900  1.989041  1.622371  1.602269

In [57]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.246267    0.617953    1.392900   -0.160673   -0.370925   -0.197939
B    1.989041    0.780909   -1.336249   -0.480174    0.623369   -0.783883
C    1.622371    0.144204   -0.314047   -0.598889    0.636178   -0.887962
D   -1.655383   -1.009016    1.602269   -0.285122    0.077903   -0.654281

In [58]:
df.sort_index(axis=1, ascending=False)


D         C         B         A
2013-01-01 -1.655383  1.622371  1.989041  0.246267
2013-01-02 -1.009016  0.144204  0.780909  0.617953
2013-01-03  1.602269 -0.314047 -1.336249  1.392900
2013-01-04 -0.285122 -0.598889 -0.480174 -0.160673
2013-01-05  0.077903  0.636178  0.623369 -0.370925
2013-01-06 -0.654281 -0.887962 -0.783883 -0.197939

In [59]:
df.sort_values(by='B')


A         B         C         D
2013-01-03  1.392900 -1.336249 -0.314047  1.602269
2013-01-06 -0.197939 -0.783883 -0.887962 -0.654281
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122
2013-01-05 -0.370925  0.623369  0.636178  0.077903
2013-01-02  0.617953  0.780909  0.144204 -1.009016
2013-01-01  0.246267  1.989041  1.622371 -1.655383

In [60]:
df['A']


2013-01-01    0.246267
2013-01-02    0.617953
2013-01-03    1.392900
2013-01-04   -0.160673
2013-01-05   -0.370925
2013-01-06   -0.197939
Freq: D, Name: A, dtype: float64

In [61]:
df[0:3]

A         B         C         D
2013-01-01  0.246267  1.989041  1.622371 -1.655383
2013-01-02  0.617953  0.780909  0.144204 -1.009016
2013-01-03  1.392900 -1.336249 -0.314047  1.602269

In [62]:
df['20130102':'20130104']


A         B         C         D
2013-01-02  0.617953  0.780909  0.144204 -1.009016
2013-01-03  1.392900 -1.336249 -0.314047  1.602269
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122

In [63]:
df.loc[dates[0]]

A    0.246267
B    1.989041
C    1.622371
D   -1.655383
Name: 2013-01-01 00:00:00, dtype: float64

In [64]:
df.loc[:, ["A", "B"]]


A         B
2013-01-01  0.246267  1.989041
2013-01-02  0.617953  0.780909
2013-01-03  1.392900 -1.336249
2013-01-04 -0.160673 -0.480174
2013-01-05 -0.370925  0.623369
2013-01-06 -0.197939 -0.783883

In [65]:
df.at[dates[0], 'A']


0.2462670523922099

In [66]:
 df.iloc[3]


A   -0.160673
B   -0.480174
C   -0.598889
D   -0.285122
Name: 2013-01-04 00:00:00, dtype: float64

In [67]:
df[df['A'] > 0]


A         B         C         D
2013-01-01  0.246267  1.989041  1.622371 -1.655383
2013-01-02  0.617953  0.780909  0.144204 -1.009016
2013-01-03  1.392900 -1.336249 -0.314047  1.602269

In [68]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))


In [69]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [70]:
df['F'] = s1


In [71]:
df

A         B         C         D    F
2013-01-01  0.246267  1.989041  1.622371 -1.655383  NaN
2013-01-02  0.617953  0.780909  0.144204 -1.009016  1.0
2013-01-03  1.392900 -1.336249 -0.314047  1.602269  2.0
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122  3.0
2013-01-05 -0.370925  0.623369  0.636178  0.077903  4.0
2013-01-06 -0.197939 -0.783883 -0.887962 -0.654281  5.0

In [72]:
df.fillna(value=5)

A         B         C         D    F
2013-01-01  0.246267  1.989041  1.622371 -1.655383  5.0
2013-01-02  0.617953  0.780909  0.144204 -1.009016  1.0
2013-01-03  1.392900 -1.336249 -0.314047  1.602269  2.0
2013-01-04 -0.160673 -0.480174 -0.598889 -0.285122  3.0
2013-01-05 -0.370925  0.623369  0.636178  0.077903  4.0
2013-01-06 -0.197939 -0.783883 -0.887962 -0.654281  5.0

In [73]:
pd.isna(df)

A      B      C      D      F
2013-01-01  False  False  False  False   True
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False  False
2013-01-04  False  False  False  False  False
2013-01-05  False  False  False  False  False
2013-01-06  False  False  False  False  False

In [74]:
df.mean()


A    0.254597
B    0.132169
C    0.100309
D   -0.320605
F    3.000000
dtype: float64

In [75]:
df.mean(axis=1)


2013-01-01    0.550574
2013-01-02    0.306810
2013-01-03    0.668975
2013-01-04    0.295028
2013-01-05    0.993305
2013-01-06    0.495187
Freq: D, dtype: float64

In [76]:
df.apply(np.cumsum)

A         B         C         D     F
2013-01-01  0.246267  1.989041  1.622371 -1.655383   NaN
2013-01-02  0.864220  2.769950  1.766575 -2.664399   1.0
2013-01-03  2.257120  1.433702  1.452528 -1.062131   3.0
2013-01-04  2.096447  0.953528  0.853639 -1.347253   6.0
2013-01-05  1.725522  1.576897  1.489818 -1.269350  10.0
2013-01-06  1.527583  0.793014  0.601856 -1.923631  15.0

In [77]:
df.apply(lambda x: x.max() - x.min())


A    1.763825
B    3.325289
C    2.510333
D    3.257652
F    4.000000
dtype: float64

In [78]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

In [79]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [80]:
df = pd.DataFrame(np.random.randn(10, 4))


In [81]:
df

0         1         2         3
0 -0.067382  0.882148  0.868840  0.336886
1 -0.084769  0.664199  0.907972 -0.589513
2 -1.101599 -0.635754  2.034735 -0.801006
3 -1.161684  0.931134  0.263672  0.628022
4 -1.105327  0.518964 -0.097384  1.039860
5 -0.076878 -1.465875  1.760561 -1.075042
6 -1.919208  0.499476 -0.926883  1.353055
7 -1.525982  0.231861 -0.125767  1.229975
8  0.732977 -0.721244 -0.497716  1.406749
9 -1.805513  0.089302 -0.366929  2.499762

In [82]:
pieces = [df[:3], df[3:7], df[7:]]


In [83]:
pieces

[          0         1         2         3
 0 -0.067382  0.882148  0.868840  0.336886
 1 -0.084769  0.664199  0.907972 -0.589513
 2 -1.101599 -0.635754  2.034735 -0.801006,
           0         1         2         3
 3 -1.161684  0.931134  0.263672  0.628022
 4 -1.105327  0.518964 -0.097384  1.039860
 5 -0.076878 -1.465875  1.760561 -1.075042
 6 -1.919208  0.499476 -0.926883  1.353055,
           0         1         2         3
 7 -1.525982  0.231861 -0.125767  1.229975
 8  0.732977 -0.721244 -0.497716  1.406749
 9 -1.805513  0.089302 -0.366929  2.499762]

In [84]:
pd.concat(pieces)

0         1         2         3
0 -0.067382  0.882148  0.868840  0.336886
1 -0.084769  0.664199  0.907972 -0.589513
2 -1.101599 -0.635754  2.034735 -0.801006
3 -1.161684  0.931134  0.263672  0.628022
4 -1.105327  0.518964 -0.097384  1.039860
5 -0.076878 -1.465875  1.760561 -1.075042
6 -1.919208  0.499476 -0.926883  1.353055
7 -1.525982  0.231861 -0.125767  1.229975
8  0.732977 -0.721244 -0.497716  1.406749
9 -1.805513  0.089302 -0.366929  2.499762

In [85]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

In [86]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [87]:
 pd.merge(left, right, on="key")


key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [88]:
df.groupby(1).sum()

0         2         3
1                                      
-1.465875 -0.076878  1.760561 -1.075042
-0.721244  0.732977 -0.497716  1.406749
-0.635754 -1.101599  2.034735 -0.801006
 0.089302 -1.805513 -0.366929  2.499762
 0.231861 -1.525982 -0.125767  1.229975
 0.499476 -1.919208 -0.926883  1.353055
 0.518964 -1.105327 -0.097384  1.039860
 0.664199 -0.084769  0.907972 -0.589513
 0.882148 -0.067382  0.868840  0.336886
 0.931134 -1.161684  0.263672  0.628022

In [89]:
df.sort_values(by=1)

0         1         2         3
5 -0.076878 -1.465875  1.760561 -1.075042
8  0.732977 -0.721244 -0.497716  1.406749
2 -1.101599 -0.635754  2.034735 -0.801006
9 -1.805513  0.089302 -0.366929  2.499762
7 -1.525982  0.231861 -0.125767  1.229975
6 -1.919208  0.499476 -0.926883  1.353055
4 -1.105327  0.518964 -0.097384  1.039860
1 -0.084769  0.664199  0.907972 -0.589513
0 -0.067382  0.882148  0.868840  0.336886
3 -1.161684  0.931134  0.263672  0.628022