#**Experiment 1: Introduction To Numpy And Introduction To Pandas**

# 1.1 Introduction To Numpy

In [1]:
import numpy as np  #importing numpy into notebook

In [2]:
a = np.arange(15).reshape(3, 5)  #arranging numbers from 0-14 into 3*5 matrix 
a.shape  #displaying shape of array


(3, 5)

In [3]:
 a.ndim   #no of dimensions of array

2

In [4]:
a.dtype.name  #data types of array

'int64'

In [5]:
 a.itemsize   #size of element in an array

8

In [6]:
a.size     #no of elements in an array

15

In [7]:
type(a)   #type of matrix


numpy.ndarray

In [8]:
 b = np.array([6, 7, 8])  #creating new array b


In [9]:
b  #printing array b


array([6, 7, 8])

In [10]:
type(b)  #type of array


numpy.ndarray

In [11]:
b.dtype  #datatype of b


dtype('int64')

In [12]:
c = np.array([[1, 2], [3, 4]], dtype=complex)  #creating a new array and converting datatype into complex


In [13]:
c   #printing array c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
c.dtype.name #datatype of c

'complex128'

In [15]:
np.zeros((3, 4)) #creating a matrix of 3 rows and 4 columns with all elements 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 3, 4), dtype=np.int16)  #creating two arrays of 3*4 matrix containing all elements 1

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty((2, 3)) #creating an array of 2*3 with random numbers


array([[4.68580766e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [18]:
np.eye(7)  #creating an identity matrix of 7*7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.arange(10, 30, 5)  #arranges the given numbers with step of 5

array([10, 15, 20, 25])

In [20]:
np.arange(0, 2, 0.3)  #arranges the given numbers with step of 0.3


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [21]:
np.linspace(0, 2, 9)  #9 equidistant values between 0-2


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
np.arange(0, 11, 1)**2  #arranging the square of numbers 0-10 in an array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [23]:
print(a) #printing a matrix


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
print(a.reshape(5, 3))  #printing matrix after reshaping


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [25]:
print(np.arange(10000)) 

[   0    1    2 ... 9997 9998 9999]


In [26]:
A = np.array([[1, 1], [0, 1]])  #arithmetic operation on matrix A & B
B = np.array([[2, 0], [3, 4]])


In [27]:
A+B

array([[3, 1],
       [3, 5]])

In [28]:
A-B

array([[-1,  1],
       [-3, -3]])

In [29]:
A*B

array([[2, 0],
       [0, 4]])

In [30]:
A @ B

array([[5, 4],
       [3, 4]])

In [31]:
A/B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.5 ,  inf],
       [0.  , 0.25]])

In [32]:
 np.sin(np.arange(0, 2 * np.pi, np.pi / 6))  #sin of values in matrix

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  5.00000000e-01,  1.22464680e-16, -5.00000000e-01,
       -8.66025404e-01, -1.00000000e+00, -8.66025404e-01, -5.00000000e-01])

In [33]:
A.dot(B)  #dot product of matrix


array([[5, 4],
       [3, 4]])

In [34]:
a[:6:2]  

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [35]:
a[::-1]


array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [36]:
a.T #transpose of matrix


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [37]:
 A.trace() #sum of diagonal elements

2

In [38]:
A[0][[False, True]]


array([1])

# 1.2 Introduction To Pandas

In [39]:
import pandas as pd  #importing pandas in notebook

In [40]:
s = pd.Series([1,3, 5, np.nan, 6, 8])  #creates a new dataframe


In [41]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [42]:
dates = pd.date_range('20130101', periods=6)  #creates database of dates


In [43]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [44]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))  #creating new dataframe


In [45]:
df

A         B         C         D
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791
2013-01-03 -0.762183  0.493651  0.292886  0.566268
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963
2013-01-05  0.555460  1.265124  1.382343 -0.423750
2013-01-06  0.174468 -0.046051 -0.162930  0.011305

In [46]:
#creating a new dataframe
df2 = pd.DataFrame({
'A' : 1.0,
'B' : pd.Timestamp('20130102'),
'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
'D' : np.array([3] * 4, dtype='int32'),
'E' : pd.Categorical(['test', 'train', 'test', 'train']),
'F' : 'foo'
})

In [47]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [48]:
df2.dtypes  #datatypes of elements in database

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [49]:
df.head(5)   #displaying first 5 rows of database

A         B         C         D
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791
2013-01-03 -0.762183  0.493651  0.292886  0.566268
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963
2013-01-05  0.555460  1.265124  1.382343 -0.423750

In [50]:
df.tail(3)  #displaying last 3 rows of database

A         B         C         D
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963
2013-01-05  0.555460  1.265124  1.382343 -0.423750
2013-01-06  0.174468 -0.046051 -0.162930  0.011305

In [51]:
df.index  #displaying index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [52]:
df.columns  #displaying column labels

Index(['A', 'B', 'C', 'D'], dtype='object')

In [53]:
df.to_numpy()  #arranges database as an array

array([[-1.21836183, -1.19925325, -1.36464582,  0.70874937],
       [-0.34748634, -0.84900262,  1.26171755, -0.99679136],
       [-0.76218313,  0.4936509 ,  0.29288606,  0.56626754],
       [-0.94310382, -0.62145781,  1.26140714, -0.42496297],
       [ 0.55546027,  1.26512435,  1.38234318, -0.42375022],
       [ 0.17446822, -0.04605087, -0.16293014,  0.01130523]])

In [54]:
df2.to_numpy()


array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [55]:
df.describe()  #displaying detailed statistics

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.423534 -0.159498  0.445130 -0.093197
std    0.683843  0.920754  1.084407  0.651882
min   -1.218362 -1.199253 -1.364646 -0.996791
25%   -0.897874 -0.792116 -0.048976 -0.424660
50%   -0.554835 -0.333754  0.777147 -0.206222
75%    0.043980  0.358725  1.261640  0.427527
max    0.555460  1.265124  1.382343  0.708749

In [56]:
df.T  #transposes the database

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.218362   -0.347486   -0.762183   -0.943104    0.555460    0.174468
B   -1.199253   -0.849003    0.493651   -0.621458    1.265124   -0.046051
C   -1.364646    1.261718    0.292886    1.261407    1.382343   -0.162930
D    0.708749   -0.996791    0.566268   -0.424963   -0.423750    0.011305

In [57]:
df.sort_index(axis=1, ascending=False)


D         C         B         A
2013-01-01  0.708749 -1.364646 -1.199253 -1.218362
2013-01-02 -0.996791  1.261718 -0.849003 -0.347486
2013-01-03  0.566268  0.292886  0.493651 -0.762183
2013-01-04 -0.424963  1.261407 -0.621458 -0.943104
2013-01-05 -0.423750  1.382343  1.265124  0.555460
2013-01-06  0.011305 -0.162930 -0.046051  0.174468

In [58]:
df.sort_values(by='B')  #sorting the databases according to ascending of column B

A         B         C         D
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963
2013-01-06  0.174468 -0.046051 -0.162930  0.011305
2013-01-03 -0.762183  0.493651  0.292886  0.566268
2013-01-05  0.555460  1.265124  1.382343 -0.423750

In [59]:
df['A']  #displaying column values of A

2013-01-01   -1.218362
2013-01-02   -0.347486
2013-01-03   -0.762183
2013-01-04   -0.943104
2013-01-05    0.555460
2013-01-06    0.174468
Freq: D, Name: A, dtype: float64

In [60]:
df[0:3]  #displaying columns in given range

A         B         C         D
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791
2013-01-03 -0.762183  0.493651  0.292886  0.566268

In [61]:
df['20130102':'20130104']  #displaying data in given date range


A         B         C         D
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791
2013-01-03 -0.762183  0.493651  0.292886  0.566268
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963

In [62]:
df.loc[dates[0]]  #values at index 0 in date columns

A   -1.218362
B   -1.199253
C   -1.364646
D    0.708749
Name: 2013-01-01 00:00:00, dtype: float64

In [63]:
df.loc[:, ["A", "B"]]  #displaying values of column A and B

A         B
2013-01-01 -1.218362 -1.199253
2013-01-02 -0.347486 -0.849003
2013-01-03 -0.762183  0.493651
2013-01-04 -0.943104 -0.621458
2013-01-05  0.555460  1.265124
2013-01-06  0.174468 -0.046051

In [64]:
df.at[dates[0], 'A']  #displaying values of column A at index 0


-1.2183618301835726

In [65]:
 df.iloc[3]


A   -0.943104
B   -0.621458
C    1.261407
D   -0.424963
Name: 2013-01-04 00:00:00, dtype: float64

In [66]:
df[df['A'] > 0]  #display rows where A>0


A         B         C         D
2013-01-05  0.555460  1.265124  1.382343 -0.423750
2013-01-06  0.174468 -0.046051 -0.162930  0.011305

In [67]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))  #create new series


In [68]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [69]:
df['F'] = s1


In [70]:
df

A         B         C         D    F
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749  NaN
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791  1.0
2013-01-03 -0.762183  0.493651  0.292886  0.566268  2.0
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963  3.0
2013-01-05  0.555460  1.265124  1.382343 -0.423750  4.0
2013-01-06  0.174468 -0.046051 -0.162930  0.011305  5.0

In [71]:
df.fillna(value=5)

A         B         C         D    F
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749  5.0
2013-01-02 -0.347486 -0.849003  1.261718 -0.996791  1.0
2013-01-03 -0.762183  0.493651  0.292886  0.566268  2.0
2013-01-04 -0.943104 -0.621458  1.261407 -0.424963  3.0
2013-01-05  0.555460  1.265124  1.382343 -0.423750  4.0
2013-01-06  0.174468 -0.046051 -0.162930  0.011305  5.0

In [72]:
pd.isna(df)

A      B      C      D      F
2013-01-01  False  False  False  False   True
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False  False
2013-01-04  False  False  False  False  False
2013-01-05  False  False  False  False  False
2013-01-06  False  False  False  False  False

In [73]:
df.mean()  #displays mean value of columns


A   -0.423534
B   -0.159498
C    0.445130
D   -0.093197
F    3.000000
dtype: float64

In [74]:
df.mean(axis=1)


2013-01-01   -0.768378
2013-01-02    0.013687
2013-01-03    0.518124
2013-01-04    0.454377
2013-01-05    1.355836
2013-01-06    0.995358
Freq: D, dtype: float64

In [75]:
df.apply(np.cumsum)  

A         B         C         D     F
2013-01-01 -1.218362 -1.199253 -1.364646  0.708749   NaN
2013-01-02 -1.565848 -2.048256 -0.102928 -0.288042   1.0
2013-01-03 -2.328031 -1.554605  0.189958  0.278226   3.0
2013-01-04 -3.271135 -2.176063  1.451365 -0.146737   6.0
2013-01-05 -2.715675 -0.910938  2.833708 -0.570488  10.0
2013-01-06 -2.541207 -0.956989  2.670778 -0.559182  15.0

In [76]:
df.apply(lambda x: x.max() - x.min())  #displaying the difference of max and min values in columns


A    1.773822
B    2.464378
C    2.746989
D    1.705541
F    4.000000
dtype: float64

In [77]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])  #create new series

In [78]:
s.str.lower()  #converts all strings to lower case

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [79]:
df = pd.DataFrame(np.random.randn(10, 4))


In [80]:
df

0         1         2         3
0 -0.748284 -0.366640 -0.449347  1.352257
1 -0.018000  2.754425  0.751890  0.173320
2 -0.486118 -2.203426  0.581212 -0.490598
3 -0.317439 -0.682573 -0.045825 -1.576252
4  0.551626 -0.641317  0.066266  0.034100
5 -0.953354 -0.130712  0.456001  0.353682
6  0.672217  1.284281  0.047272  1.413660
7  1.432509  0.441018 -0.153903  1.616332
8 -0.988989  1.851011 -0.400980  0.396014
9  1.010814  0.715918 -0.083834 -1.269178

In [81]:
pieces = [df[:3], df[3:7], df[7:]]


In [82]:
pieces

[          0         1         2         3
 0 -0.748284 -0.366640 -0.449347  1.352257
 1 -0.018000  2.754425  0.751890  0.173320
 2 -0.486118 -2.203426  0.581212 -0.490598,
           0         1         2         3
 3 -0.317439 -0.682573 -0.045825 -1.576252
 4  0.551626 -0.641317  0.066266  0.034100
 5 -0.953354 -0.130712  0.456001  0.353682
 6  0.672217  1.284281  0.047272  1.413660,
           0         1         2         3
 7  1.432509  0.441018 -0.153903  1.616332
 8 -0.988989  1.851011 -0.400980  0.396014
 9  1.010814  0.715918 -0.083834 -1.269178]

In [83]:
pd.concat(pieces)

0         1         2         3
0 -0.748284 -0.366640 -0.449347  1.352257
1 -0.018000  2.754425  0.751890  0.173320
2 -0.486118 -2.203426  0.581212 -0.490598
3 -0.317439 -0.682573 -0.045825 -1.576252
4  0.551626 -0.641317  0.066266  0.034100
5 -0.953354 -0.130712  0.456001  0.353682
6  0.672217  1.284281  0.047272  1.413660
7  1.432509  0.441018 -0.153903  1.616332
8 -0.988989  1.851011 -0.400980  0.396014
9  1.010814  0.715918 -0.083834 -1.269178

In [84]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

In [85]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [86]:
 pd.merge(left, right, on="key")


key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [87]:
df.groupby(1).sum()

0         2         3
1                                      
-2.203426 -0.486118  0.581212 -0.490598
-0.682573 -0.317439 -0.045825 -1.576252
-0.641317  0.551626  0.066266  0.034100
-0.366640 -0.748284 -0.449347  1.352257
-0.130712 -0.953354  0.456001  0.353682
 0.441018  1.432509 -0.153903  1.616332
 0.715918  1.010814 -0.083834 -1.269178
 1.284281  0.672217  0.047272  1.413660
 1.851011 -0.988989 -0.400980  0.396014
 2.754425 -0.018000  0.751890  0.173320

In [88]:
df.sort_values(by=1)

0         1         2         3
2 -0.486118 -2.203426  0.581212 -0.490598
3 -0.317439 -0.682573 -0.045825 -1.576252
4  0.551626 -0.641317  0.066266  0.034100
0 -0.748284 -0.366640 -0.449347  1.352257
5 -0.953354 -0.130712  0.456001  0.353682
7  1.432509  0.441018 -0.153903  1.616332
9  1.010814  0.715918 -0.083834 -1.269178
6  0.672217  1.284281  0.047272  1.413660
8 -0.988989  1.851011 -0.400980  0.396014
1 -0.018000  2.754425  0.751890  0.173320